gsb_frais_login:
    path:     /GSB/login/{name}
    defaults: { _controller: LoginController:Default:index }

gsb_frais_homepage:
  path:     /GSB/visiteur/{name}
  defaults: { _controller: VisiteurController:Default:index }

gsb_frais_homepage:
    path:     /GSB/comptable/{name}
    defaults: { _controller: ComptableController:Default:index }

