parameters:
#    gsb_frais.example.class: GSB__Frais_MVC\GSBFraisBundle\Example

services:
#    gsb_frais.example:
#        class: %gsb_frais.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
