Epsi\Bundle\BlogBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: Epsi\Bundle\BlogBundle\Entity\CommentRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        date:
            type: datetime
        comment:
            type: text
    lifecycleCallbacks: {  }
