Epsi\Bundle\BlogBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Epsi\Bundle\BlogBundle\Entity\UserRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        username:
            type: string
            length: '30'
        email:
            type: string
            length: '100'
        password:
            type: string
            length: '100'
    lifecycleCallbacks: {  }
